# In Gateway resources it's not possible to configure autoscaling and/or the amount of replicas
# This should be done with a separate HPA like the one below
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: public-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: public-gateway-istio
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
