apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 30m
  driftDetection:
    # set to warn as we've got some Istio automated post-deployment 
    # patching happening which causes drift correction loops
    mode: warn
  chart:
    spec:
      chart: istiod
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    pilot:
      env:
        # for now required for Gateway-API TLSRoute support
        PILOT_ENABLE_ALPHA_GATEWAY_API: true
    seccompProfile:
      type: RuntimeDefault
