apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-controller
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: kyverno
      version: "3.5.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 12h
  values:
    features:
      backgroundScan:
        # enforce resource filters in background scans to avoid flooding event logs
        # with entries for namespaces already excluded in the admission flow.
        skipResourceFilters: false 
