apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno-policy-reporter
  namespace: set-in-overlay
spec:
  interval: 24h
  url: https://kyverno.github.io/policy-reporter
