apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policy-reporter
spec:
  interval: 3m
  chart:
    spec:
      chart: policy-reporter
      version: "3.5.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno-policy-reporter
      interval: 12h
  values:
    metrics:
      enabled: true
    reportFilter:
      namespaces:
        exclude: ["kube-system"]
    ui:
      enabled: true
    plugin:
      kyverno:
        enabled: true
    monitoring:
      enabled: true
      grafana:
        dashboards:
          enabled: true
        grafanaDashboard:
          enabled: true
