apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  chart:
    spec:
      version: "5.5.1"
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: s3-credentials
    mimir:
      structuredConfig:
        limits:
          max_queriers_per_tenant: 2
          compactor_blocks_retention_period: 7d
          max_global_series_per_user: 1000000
          ingestion_rate: 50000
          ingestion_burst_size: 400000
        common:
          storage:
            backend: s3
            s3:
              endpoint: s3.eu-west-par.io.cloud.ovh.net
              secret_access_key: "${S3_SECRET_ACCESS_KEY}"
              access_key_id: "${S3_ACCESS_KEY_ID}"
        blocks_storage:
          s3:
            bucket_name: havenplus-mimir-blocks
        alertmanager_storage:
          s3:
            bucket_name: havenplus-mimir-alertmanager
        ruler_storage:
          s3:
            bucket_name: havenplus-mimir-ruler
    compactor:
      persistentVolume:
        size: 50Gi
    store_gateway:
      persistentVolume:
        size: 20Gi
    ingester:
      persistentVolume:
        size: 50Gi
