apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  values:
    global:
      podLabels:
        "azure.workload.identity/use": "true"
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: "3fe775ff-8bc2-4da8-bbf5-60c45853a3e4"
    mimir:
      structuredConfig:
        common:
          storage:
            azure:
              account_name: akshavenplus
        blocks_storage:
          azure:
            container_name: havenplus-mimir-blocks
        alertmanager_storage:
          azure:
            container_name: havenplus-mimir-alertmanager
        ruler_storage:
          azure:
            container_name: havenplus-mimir-ruler
