apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-demo
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/tenant-demo/
  prune: true
  dependsOn:
    - name: kyverno-policies
