apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
spec:
  chart:
    spec:
      version: "5.5.1"
  values:
    minio:
      enabled: true
    ruler_querier:
      replicas: 1
    ingester:
      replicas: 1
    querier:
      replicas: 1
    store_gateway:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    query_scheduler:
      replicas: 1