apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno-policies
      version: "3.4.4"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 12h
  values:
    validationFailureAction: Enforce
    podSecurityStandard: "restricted"
    policyExclude:
      disallow-host-path:
        any:
        - resources:
            namespaces:
            - falco
      disallow-privileged-containers:
        any:
        - resources:
            names:
            - "falco"
