apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: kyverno-policies
      version: "3.6.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 12h
  values:
    validationFailureAction: Enforce
    podSecurityStandard: "restricted"
    policyExclude: {} # add relevant policy excludes in the concerning overlay
