apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: "set-in-overlay" # see https://artifacthub.io/packages/helm/bitnami/keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
      interval: 12h
  values:
    replicaCount: 1
    production: 
    proxyHeaders: ""
    postgresql:
      enabled: false
    externalDatabase:
      host: ""
      port:
      user: "" 
      database: ""
      password: ""
      existingSecret: "keycloak-pg-cluster-app"
      existingSecretHostKey: "host"
      existingSecretPortKey: "port"
      existingSecretUserKey: "user"
      existingSecretDatabaseKey: "dbname"
      existingSecretPasswordKey: "password"
    auth:
      adminUser: "iac-admin"
      existingSecret: "keycloak"
      passwordSecretKey: "KEYCLOAK_ADMIN_PASSWORD"