apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
spec:
  values:
    extraVolumes:
      - name: service-key-secret
        secret:
          secretName: azure-service-key
    opencost:
      exporter:
        extraVolumeMounts:
          - mountPath: /var/secrets
            name: service-key-secret
