apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  releaseName: trivy-operator
  interval: 30m
  chart:
    spec:
      chart: trivy-operator
      version: "0.28.1" # see https://artifacthub.io/packages/helm/trivy-operator/trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
        namespace: trivy-system
  values:
    serviceMonitor:
      enabled: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
    trivyOperator:
      scanJobPodTemplateContainerSecurityContext:
        seccompProfile:
          type: RuntimeDefault
