apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/external-secrets/overlays/lab-clusters/cyso-pdv
  prune: true
  wait: true
  dependsOn:
    - name: cluster-resources
    - name: kyverno-policies
