---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: ""
  template:
    metadata:
      name: keycloak
      namespace: keycloak
    type: Opaque
