apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator
      version: 25.3.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-gpu-operator
      interval: 12h
