apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator
      version: v25.3.4
      sourceRef:
        kind: HelmRepository
        name: nvidia-gpu-operator
      interval: 12h
