apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  values:
    resources:
      # set resource requests so that sealed-secrets can run on local Kind envs
      requests:
        cpu: 1m
        memory: 1Mi
    metrics:
      serviceMonitor:
        enabled: false # disabled until we have Prometheus Operator
