apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    spec:
      version: "2.16.2"
  values:
    metrics:
      serviceMonitor:
        enabled: false # disabled until we have Prometheus Operator
