# We're installing Grafana in wave-1, as we need the CRDs
# for dashboards of other components in later waves

# CONTROLLER
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-controller
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/grafana/controller/overlays/local
  prune: true
  wait: true
  dependsOn:
    - name: kyverno-policies

---
# CONFIG
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-config
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/grafana/config/overlays/local
  prune: true
  wait: true
  dependsOn:
    - name: grafana-controller
