apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pinniped-supervisor
spec:
  commonName: "pinniped-supervisor.havenplus-azure.haven.vng.cloud"
  dnsNames:
    - "pinniped-supervisor.havenplus-azure.haven.vng.cloud"
