apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  values:
    controller:
      type: daemonset
    alloy:
      stabilityLevel: experimental
      configMap:
        name: alloy
        key: config.alloy
