apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.41.1"
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 12h
  values:
    deploymentMode: SimpleScalable
    loki:
      tracing:
        enabled: true
      analytics:
        reporting_enabled: false
      compactor:
        working_directory: /tmp/data/retention
        retention_enabled: false
      ingester:
        max_chunk_age: 12h
      querier:
        multi_tenant_queries_enabled: true
      limits_config:
        discover_service_name: ['service','app','application','name','app_kubernetes_io_name','container','container_name','component','workload','job', 'placeholder']
        ingestion_rate_mb: 16
        max_queriers_per_tenant: 2
        retention_period: 31d
      storage:
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
      storage_config: {} # set_in_overlay
      schemaConfig: {} # set_in_overlay
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    lokiCanary:
      push: true
    write:
      extraArgs:
        - -config.expand-env=true
    read:
      extraArgs:
        - -config.expand-env=true
    backend:
      extraArgs:
        - -config.expand-env=true
    gateway:
      containerSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    adminApi:
      containerSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    memcached:
      containerSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    memcachedExporter:
      containerSecurityContext:
        seccompProfile:
          type: RuntimeDefault
