apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-server-provisioner
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: nfs-server-provisioner
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: nfs-ganesha-server-and-external-provisioner
      interval: 12h
  values:
    persistence:
      enabled: true
      size: 100Gi
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
