apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-operator
spec:
  values:
    watchNamespaces:
      - keycloak-instances
      - tenant-fieldlab-nov2025 # temporary for field lab
