apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
spec:
  values:
    nfs:
      server: set-in-overlay
      path: set-in-overlay
    storageClass:
      name: previder-staas
