apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: 1.27.0
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
