apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/nfs-subdir-external-provisioner/overlays/previder
  prune: true
  wait: true
  dependsOn:
    - name: cluster-resources
    - name: kyverno-policies
