apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: pinniped
      version: 2.4.23 # see https://artifacthub.io/packages/helm/bitnami/pinniped
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values:
    supervisor:
      enabled: false
