apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped
spec:
  interval: 30m
  driftDetection:
    mode: disabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: pinniped
      version: 2.4.23 # see https://artifacthub.io/packages/helm/bitnami/pinniped
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      registry: ghcr.io
      repository: vmware/pinniped/pinniped-server
      tag: v0.42.0 # see https://github.com/vmware/pinniped/releases
      digest: "sha256:7f901305b659e9ed3c5b32ab273141430202f2b5fa697616574753a96c845537"
    supervisor:
      enabled: false
