apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pinniped-supervisor
spec:
  commonName: set-in-overlay
  dnsNames:
    - set-in-overlay
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: pinniped-supervisor-tls
