apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  values:
    serviceAccount:
      annotations:
        "azure.workload.identity/client-id": "a1cd866b-4171-4b28-a91c-ece79747137e"
    loki:
      podLabels:
        azure.workload.identity/use: "true"
      storage:
        azure:
          accountName: "akshavenplus"
