apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  chart:
    spec:
      version: "3.4.4"
  values:
    policyExclude:
      disallow-capabilities:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-host-namespaces:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - trivy-system
      disallow-host-path:
        any:
        - resources:
            namespaces:
            - falco
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-host-ports:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-host-process:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-privileged-containers:
        any:
        - resources:
            namespaces:
            - falco
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-proc-mount:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-selinux:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      restrict-apparmor-profiles:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      restrict-seccomp:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      restrict-sysctls:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
      disallow-capabilities-strict:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - falco
      disallow-privilege-escalation:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - falco
      require-run-as-non-root-user:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - falco
            - trivy-system
      require-run-as-nonroot:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - falco
            - trivy-system
      restrict-seccomp-strict:
        any:
        - resources:
            namespaces:
            - flux-system # https://github.com/fluxcd/source-controller/issues/582
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - falco
      restrict-volume-types:
        any:
        - resources:
            namespaces:
            - calico-*
            - openshift-*
            - quattro-*
            - tigera-operator
            - falco
