apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-pg-cluster
spec:
  instances: 1
  enablePDB: false
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
  storage:
    size: 2Gi
