apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: havenplus-realm-import
spec:
  keycloakCRName: keycloak
  realm:
    realm: matlab035
    enabled: true
    groups:
      - name: k8s-admins
        path: /k8s-admins
      - name: k8s-developers
        path: /k8s-developers
    clients:
      - clientId: pinniped-cli
        name: Pinniped CLI
        description: OIDC client for Pinniped CLI authentication
        enabled: true
        publicClient: true
        directAccessGrantsEnabled: true
        standardFlowEnabled: true
        implicitFlowEnabled: false
        serviceAccountsEnabled: false
        redirectUris:
          - "http://127.0.0.1:*"
          - "http://localhost:*"
        webOrigins:
          - "*"
        protocol: openid-connect
        defaultClientScopes:
          - email
        optionalClientScopes: []
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            consentRequired: false
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              claim.name: groups
              userinfo.token.claim: "true"
