apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 30m
  chart:
    spec:
      chart: cni
      version: 1.27.2
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    profile: ambient
    seccompProfile:
      type: RuntimeDefault
