apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: cni
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
  values:
    profile: ambient
    seccompProfile:
      type: RuntimeDefault
