apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: ztunnel
      version: 1.27.3
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
