apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  chart:
    spec:
      version: "10.0.5"
  values:
    deployNodeAgent: false
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
    credentials:
      existingSecret: s3-credentials
    configuration:
      features: EnableCSI
      uploaderType: "kopia"
      defaultBackupStorageLocation: "cyso-s3"
      logLevel: "warning"
      backupStorageLocation: 
      - name: "cyso-s3"
        default: true
        provider: "aws"
        bucket: "velero"
        credential:
          name: "s3-credentials"
          key: "cloud"
        config: 
          region: "core"
          s3ForcePathStyle: "true"
          s3Url: https://core.fuga.cloud:8080        
