apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
spec:
  parentRefs:
  - name: public-gateway
    namespace: istio-gateway
  hostnames:
  - "keycloak.havenplus-azure.haven.vng.cloud"
  rules:
  - backendRefs:
    - name: keycloak-service
      port: 8080
