---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: keycloak-instances
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgAfgphu4gunyDSQl6Ivlxdlu4yU5cilDNzRidrAzPINY5CsTNz8NKmi0ZmQEUA/I5GzF9oFnWrtrYrNtrX5isevxTznIvA82trSKOHA2F0oeMqi+yfuzcBdcRbhuMqfIKrTkIb4bQSwOspCY7zT3gU4bwV+d1Xq5TpibwQlOXVCqkuz6q6kfbzgBozizGRq/q1X2BCtTQiV7apPq0xsb4ItwGJbo1aKPtlhnb58Gr+ci2sNH0aplIEcfhJ6ZJNuEh59P6ly43gbjAAycwQs56AehDjACPRG/qO5tNNKU0bwfFOT3Fplc4eFOZ/Z7z67i2VJ8SaCJ1b54Dxy9pUbRrVvBjvF57Ogni4EUEXbfEOJaLkClXg1WmF7Qu805Pwjt8jmlomZFM32vlbYET+1CXKiMPbxNgV8MtNDi6B8dxa8Uj+Rf10Q/iYRb4QQKBQplV4zAqfFTyy0wlDHwLN5wyT7xClZJsLcsc/T/9Di6HvZY4f+mSGuIpmT60ZQhweUIDuW0TCkCqezKBqHO/Tl57y4EivO8popc1w+4gsehpIQuQlW1ds+Ed137NCxAN+yvxXnLmenNjyXiY0IXYb7Iwn1Y7n1nK+4ioJ0cr8UCV+PjN0s24TYGgNO3pbfwocmX8AsbfSqx+V2sbOJpJ4ttufSoay0M5bASWMErlGWLVyr1tVeC01eyrJ7/kuziWm6yCM/cfWJNy8gGX9erMmWREmF16cyFhFbhic6S3AvQVXYBA==
  template:
    metadata:
      name: keycloak
      namespace: keycloak-instances
    type: Opaque
