apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 30m
  driftDetection:
    # set to warn as we've got some Istio automated post-deployment 
    # patching happening which causes drift correction loops
    mode: warn
  chart:
    spec:
      chart: base
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 12h
