apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  values:
    metrics:
      serviceMonitor:
        enabled: false # disabled until we have Prometheus Operator
    ingress:
      enabled: true
      path: /v1/cert.pem
      pathType: ImplementationSpecific
      ingressClassName: nginx
      hostname: public-key.example.domain.tld
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls: true
    resourcesPreset: "medium"
    readinessProbe:
      enabled: true
      initialDelaySeconds: 90
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
