apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    spec:
      version: "2.16.2"
  values:
    metrics:
      serviceMonitor:
        enabled: false # disabled until we have Prometheus Operator
    ingress:
      enabled: true
      path: /v1/cert.pem
      pathType: ImplementationSpecific
      ingressClassName: nginx
      hostname: public-key.example.domain.tld
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls: true
