apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  chart:
    spec:
      chart: kube-state-metrics
      version: "do_override"
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
  interval: 1h
  values:
    selfMonitor:
      enabled: true
    prometheus:
      monitor:
        enabled: true
