apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: kube-state-metrics
      version: "6.3.0"
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
  values:
    selfMonitor:
      enabled: true
    prometheus:
      monitor:
        enabled: true
