---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgBK3Xxut3Weo4Enjvn1eZX9kofDB226ZI6eke0fGkPsN2pck5mKj92tqnoUDH3vMFySTr+Ux9/731oplYCDLjknHRnASYn1XhWbG/ltJLO1IAvZVFjDnNOMiccc7vvTvhoqCW1egUMVHDJKrIqFVB2xbSTu0oaWIlr5vmBtuozTZtlB5a15ktvfXWJLcDBbuCadnLf5OskYu5D4Nxnbvaii7PauSsp/DpkCegPJYCN2CVdQG2Xsd6pWUxBPdJ+1GoPNJj9FfEGm1wN/fpiNmPN3KZNGs9WopfIR3ByRkFXH983RANNIMBy5RFPFthm6umzyW4tdIsRPdr0M35lYHpXqiAasMtRWoehHClkjkDl1o5nIS8P+iKFDR1CYH/WAp9KWsrI1AKXQb5wAn7Dwp3YYYX9iCEAkU7ol9oJXBsuygkmSHc+9UzSy9gNz0P0R7yEgWuvqMZcB0Z33SwhObJKJGgoTIucT4R/CuL0Z3hJ85jBwntMGW/6VSDHPfUAWpjtcwTIpvXx8E0+YH4PpAlWcv7ZD2DGCC/XmJ0Dc8r43LEDudNnUWPx4QwvkhH/YTJoL/QrIIeIUkN+gDnmIEuxqpt1uFCyCThif1/pGAbLpBb1icA7EiE82rF3HfUfXLieknjdaNXVWADDQsBK7mKWFstdyHfyZ4bPu0VzgheKa3atp0i58Y0rfKEifUACEECzbHP6CWRnfkM8=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak
      namespace: keycloak-instances
