apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 30m
  driftDetection:
    mode: disabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: velero
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: velero
      interval: 12h
  values:
    upgradeCRDs: true
    metrics:
      serviceMonitor:
        enabled: false
    credentials:
      useSecret: true
      name: "cloud-credentials"
      secretContents: {} # set in overlay
    deployNodeAgent: true
    nodeAgent:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    snapshotsEnabled: false
    defaultBackupStorageLocation: "aws"
    uploaderType: "kopia"
    defaultVolumesToFsBackup: true
    containerSecurityContext: 
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
    kubectl:
      containerSecurityContext: 
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
