apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  values:
    deployNodeAgent: false
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
    credentials:
      existingSecret: s3-credentials
    configuration:
      features: EnableCSI
      uploaderType: "kopia"
      defaultBackupStorageLocation: "previder-s3"
      logLevel: "warning"
      backupStorageLocation:
        - name: "previder-s3"
          default: true
          provider: "aws"
          bucket: "havenplus-velero"
          credential:
            name: "s3-credentials"
            key: "cloud"
          config:
            s3ForcePathStyle: "true"
            s3Url: https://object.previder.nl
