apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eck-operator
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: eck-operator
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: eck-operator
      interval: 12h
  values:
      nameOverride: "eck-operator"
      fullnameOverride: "eck-operator"
      installCRDs: false
      replicaCount: 2
      serviceAccount:
        create: false
      global:
        manifestGen: false
        createOperatorNamespace: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

