---
# Direct SCC binding using OpenShift's format
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:haven-plus-scc:ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:haven-plus-scc
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx
  - kind: ServiceAccount
    name: ingress-nginx-admission
    namespace: ingress-nginx