apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  values:
    metrics:
      serviceMonitor:
        enabled: false # disabled until we have Prometheus Operator
