apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sealed-secrets-public-key
spec:
  parentRefs:
  - name: public-gateway
    namespace: istio-gateway
    sectionName: https
  hostnames:
  - "public-key.havenplus-azure.haven.vng.cloud"
