apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  chart:
    spec:
      version: "3.4.4"
  values:
    policyExclude:
      disallow-capabilities:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      disallow-host-namespaces:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      disallow-host-path:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - falco
            - local-path-storage
            - trivy-system
            - velero # needed for the node-agent daemonset which does file-system-backup
      disallow-host-ports:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      disallow-host-process:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      disallow-privileged-containers:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - falco
      disallow-proc-mount:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      disallow-selinux:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      restrict-apparmor-profiles:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      restrict-seccomp:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      restrict-sysctls:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
      disallow-capabilities-strict:
        any:
        - resources:
            namespaces: 
            - tenant-fieldlab-nov2025
            - local-path-storage
            - nfs-server-provisioner # needs additional capabilities to function properly
            - falco
      disallow-privilege-escalation:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - local-path-storage
            - falco
      require-run-as-non-root-user:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - trivy-system
            - nfs-server-provisioner
            - falco
            - velero
      require-run-as-nonroot:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - local-path-storage
            - trivy-system # trivy needs to be root in order to be able to scan filesystems
            - nfs-server-provisioner
            - falco
            - velero
      restrict-seccomp-strict:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - local-path-storage
            - falco
      restrict-volume-types:
        any:
        - resources:
            namespaces:
            - tenant-fieldlab-nov2025
            - falco
