apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  chart:
    spec:
      version: "6.28.0"
  values:
    serviceAccount:
      labels:
        azure.workload.identity/use: "true"
      annotations:
        "azure.workload.identity/client-id": "6ebdf2c1-0916-4a10-959f-013b477f8c20"
    write:
      replicas: 2
    read:
      replicas: 2
    backend:
      replicas: 2
    loki:
      podLabels:
        azure.workload.identity/use: "true"
      storage:
        type: azure
        azure: 
          accountName: lgtmfield
          useFederatedToken: true
      schemaConfig:
        configs: 
          - from: "2024-06-01"
            object_store: azure
            store: tsdb
            schema: v13
            index:
              prefix: index_
              period: 24h
      compactor:
        retention_enabled: true
        delete_request_store: azure
      limits_config:
        retention_period: 7d
