apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/loki/overlays/local
  prune: true
  wait: true
  dependsOn:
    - name: alloy
    - name: grafana-controller
    - name: kube-state-metrics
    