apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped
spec:
  values:
    concierge:
      credentialIssuerConfig: |
        impersonationProxy:
          mode: enabled
          externalEndpoint: example-cluster.mydomain.io:443
          service:
            type: ClusterIP
