apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinniped
spec:
  values:
    concierge:
      credentialIssuerConfig: |
        impersonationProxy:
          mode: disabled
    supervisor:
      enabled: false
