apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  values:
    controller:
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-havenplus"
          service.beta.kubernetes.io/azure-pip-name: "pip-ingress-ipv4-havenplus-0"
      extraArgs:
        enable-ssl-passthrough: "" # for pinniped
