apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  values:
    serviceAccount:
      server:
        annotations:
          azure.workload.identity/client-id: "4251dd95-c170-4d40-a5c0-861f3e1b2915"
    configuration:
      backupStorageLocation:
      - name: "azure"
        default: true
        provider: "azure"
        bucket: "havenplus-velero"
        config:
          resourceGroup: "rg-havenplus"
          storageAccount: "akshavenplus"
          subscriptionId: "f83aeed4-d795-4061-8c72-194c372b586e"
          useAAD: "true"
