allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: azurefile-premium-zrs-nfs
mountOptions:
  - nconnect=4
  - noresvport
  - actimeo=30
parameters:
  protocol: nfs
  skuName: Premium_ZRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
