apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  values:
    metrics:
      serviceMonitor:
        enabled: false # disabled until we have Prometheus Operator
    resourcesPreset: "medium"
    readinessProbe:
      enabled: true
      initialDelaySeconds: 90
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
