apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-demo
  namespace: tenant-demo
spec:
  interval: 1m0s
  path: ./local/
  prune: false
  serviceAccountName: tenant-demo
  sourceRef:
    kind: GitRepository
    name: tenant-demo
