apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: s3-credentials
    loki:
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          endpoint: core.fuga.cloud:8080
          region: core
          accessKeyId: "${S3_ACCESS_KEY_ID}"
          secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      pattern_ingester:
          enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 31d
      ruler:
        enable_api: true
    read:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
    write:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
      persistence:
        size: 20Gi
    backend:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
      persistence:
        size: 20Gi
    chunksCache:
      # by default the allocatedMem is set to 8192, which means that the Loki Helmchart automatically sets request-mem to almost 10G
      # regarding the reference implementation on the Cyso env, we do not want to push the required amount of resources too much
      # therefore we set allocatedMemory to 1024M. Do adjust this setting to your needs on your own environment. 
      allocatedMemory: 1024