apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  values:
    initContainers:
      - name: velero-plugin-for-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.13.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
    credentials:
      useSecret: false
    podLabels:
      azure.workload.identity/use: "true"
    serviceAccount:
      server:
        annotations:
          azure.workload.identity/client-id: "<client_id>"
    configuration:
      uploaderType: "kopia"
      defaultVolumesToFsBackup: true
      defaultBackupStorageLocation: "azure"
      deployNodeAgent: true
      snapshotsEnabled: false
      logLevel: "warning"
      backupStorageLocation:
      - name: "azure"
        default: true
        provider: "azure"
        bucket: "havenplus-velero"
        config:
          resourceGroup: "<resource_group>"
          storageAccount: "<storage_account>"
          subscriptionId: "<subscription_id>"
          useAAD: "true"
