apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.19.1  # see https://github.com/external-secrets/external-secrets/releases
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
