apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: external-secrets
      version: 1.0.0  # see https://github.com/external-secrets/external-secrets/releases
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
