apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
    credentials:
      secretContents:
        # static Garage key for local env ONLY!
        cloud: |
          [default]
          aws_access_key_id=GK189d726f849af84af01bdfeb
          aws_secret_access_key=f44a7eb0d58c8dd785c5494506445abe93cd75afab48fa0dd2db35bdd78a01f0
    configuration:
      # insecureSkipTLSVerify: true
      uploaderType: "kopia"
      defaultVolumesToFsBackup: true
      defaultBackupStorageLocation: "garage"
      deployNodeAgent: true
      snapshotsEnabled: false
      logLevel: "warning"
      backupStorageLocation: 
      - name: "garage"
        default: true
        provider: "aws"
        bucket: "velero"
        credential:
          name: "cloud-credentials"
          key: "cloud"
        config: 
          region: "garage"
          s3ForcePathStyle: "true"
          s3Url: http://garage.garage.svc:3900
          signatureVersion: "4"
