apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  values:
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
    credentials:
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=minio
          aws_secret_access_key=minio123
    configuration:
      # insecureSkipTLSVerify: true
      uploaderType: "kopia"
      defaultVolumesToFsBackup: true
      defaultBackupStorageLocation: "minio"
      deployNodeAgent: true
      snapshotsEnabled: false
      logLevel: "warning"
      backupStorageLocation: 
      - name: "minio"
        default: true
        provider: "aws"
        bucket: "velero"
        credential:
          name: "cloud-credentials"
          key: "cloud"
        config: 
          region: "minio"
          s3ForcePathStyle: "true"
          s3Url: http://minio.minio-generic-tenant.svc:80
          signatureVersion: "4"
