---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgB8k/gFVup2I2T1Ivnq16rc1jPhIIfzDkPBKTRI/9MXmqYbtiH84hat+uCzaMrmDPCwHwQQS8CRcFNzm77tTDlq8H3G8SEkWX2BoJhyIGiLgNoJ+cKOglsJs+fYwQeU235AOIyAyUKTIeaXYvsFaRN7VsP5qwQkqwI6R9F4z55yzdoyroSXb4pIR0PMY+173FGDa3zr74IXQ69XeL7qBltWamMzRC7dPgN0bvKh1Gk9NjUaWnXi6QKnUamAfj4x8A+lDa7GbK5E5pSQYmnQMYizVwJU484dKM43Wjw7Ika+wrOXy6hcDjff1f815UQi+xEsXDsGNjRDiXkCnmNtmvif9v0vRVvR5qIkWjkvhOfT1sFWdIoiu9HKr6uGELaxTmxUUfmq5vguvH2J9R+YGfxIEmApQlbCpaEiBg6kvoWK47qkBRM8KGclMPb8UoPrUM3PaJ4uP7JHAO7WUSFEMiVIx8LoKoclYVcZpT5ymB0QC7/cwUM42iLRovBw2prm1bhEsgv+Gqj4+sauRkKvCY9YGBb8SNE6AMtgcxOB6N1Dlz+cetfFkQyJYlBwlEOq3d+VNaJlO8Cu3Xk2opaldGTwWbJYMgfBPvZgoiIYJ1p6MFMNxFESfIQsf6lTxywQ1cZOncqQ+Jz+CYBy1CT5wx5RAfhuPuVpIJlQ2Thl0FT1eLu9fRrLOPNFmuwP8L/2zuHlGvTkF306xllDfg6UjNKlzDGTm13+BHVUfYYfNpHiZw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak
      namespace: keycloak
