apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: 1.16.2 # see https://artifacthub.io/packages/helm/cert-manager/cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 12h
  values:
    crds:
      enabled: true
    extraArgs:
      - "--enable-gateway-api=true"
