apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: cert-manager
      version: v1.19.2 # see https://artifacthub.io/packages/helm/cert-manager/cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 12h
  values:
    crds:
      enabled: true
    extraArgs:
      - "--enable-gateway-api=true"
