apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/local/
  prune: true
