apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.16.2"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 12h
  values:
    # The name is overridden, as Kubeseal expects this name by default.
    fullnameOverride: sealed-secrets-controller
    # Resources defaulted to what is prescribed in the documentation, adjust accordingly.
    # Ref: https://github.com/bitnami-labs/sealed-secrets?tab=readme-ov-file#helm-chart-on-a-restricted-environment
    resources:
      requests:
        cpu: 150m
        memory: 256Mi
      limits:
        cpu: 150m
        memory: 256Mi
    metrics:
      serviceMonitor:
        enabled: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
