apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 12h
