apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  values:
    provider:
      name: azure
    domainFilters: [] # external-dns only targets domains in this list.
    serviceAccount:
      labels:
        azure.workload.identity/use: "true"
      annotations:
        azure.workload.identity/client-id: "<FILL_CLIENT_ID>"
    podLabels:
      azure.workload.identity/use: "true"
    extraVolumes: 
      - name: azure-config-file
        secret:
          secretName: external-dns # for contents, see https://kubernetes-sigs.github.io/external-dns/latest/docs/tutorials/azure/#helm
    extraVolumeMounts: 
      - name: azure-config-file
        mountPath: /etc/kubernetes
        readOnly: true
    serviceMonitor:
      enabled: true
