---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: loki
  labels:
    havenplus.commonground.nl/sealed-secrets: ""
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgC37CvqJGjEQtysqNamPHMBv/b7jSveA6WIiY/3fFVLQU5FaD0IPDSmlJywSdI9zhs6gPbW4WzYMsJMnyh5gDYVXouBjRqhdnD0P4ZYZnEZYhxT3TtvgDMGWN2RIo66ju30bxXKsbwKLYqK1qP/QExSgPVlvTAyisZsgndXOKduj0Wz6mD1xS/j6MVO9TKKP6e5CGJpFsN9PF+x7eGPM+b8leP2BDEmGgOTWFFE6jGZhBbj+wdyqFJrtB1I6tJOykW1Gd9Nz2wmTqbEoSUCV7dddnt4+eR+xb8PE8PfzBpeChBDvMfpiLsOtS+02u3REd3g26iCI+Y1dTGbCn7uoI6D6QYOCQlgETJug5l5NhevEJIXca20+gahzuaSEYiMqwkZOKtd2VTbYp36rYport2wdc68OPaAwuOCX15KS1X2Uh7ar0XmI1QpAh1UmkdLRRf6My8Hyi51+vT52F/sFij+88cN4av2ePnd4YPe/uXSb3SXi0UWRNuoqCqpZzJQcoN238Bn0KAEWJqGZFPoARlk2UFa8Y1niVOaDITiPSHMUbb86UWcdiAuhi0PgdUC5TBELVFwaWkCIxjDcsv9Roz+DnGnYJRIXOp+pHieTxxhfQqDS0OWNbR0A/FYGFvRfvnk0EwDDdUjb0ZR6E4AmF5/ZQdhXpbz5tKmWaw+Y0ofP2001w5VO7SLPaas5nx3Fh5Ltew8lb4ZcNL4Z3onqA2Kb/0J7w==
    S3_SECRET_ACCESS_KEY: AgBQS9d3B/bK94MjZRBQUPiRtqxxfaqSAX1NAYYod8pgGjAyrvPjSrEy0gnu/gFl58VdmYlCpax2RuTQimMuFMf6BDmUlv9qGZ2WtmJEq4MdgNXWqGQXnPUyDD4uXHhkosjA4wyjwplkxxufVPDCAZ2MgClKD/9Ko50SWBS5bkfvNuA4FlUm9x69UwgqIi8Qo2XBzGXJ2DtaBlgt0fJluQW/KzhgEyKstG7FDhrRbvtL4EG3ooHdBVCuBSRlW/WNQRFD0NZ2z2I1C7BOtoEuBYwkcXzxUar7DX6dy/VQDuP3gX2FMeXpf8K0I7sBpt184csS3O8c3VCm4wRYdSqa4fyfzh/UJpSDt0WjngYZP4Un5WcJl1tdYViTDrL3ayr12TvJDh5kd9jVQHMQU+ibvrhsWNk0LBKrCVPXc+sX1Y3UJU2H7bt+qPCtAIAvyjRJa1oOJ2LAE5anTEtRmC1Yt4JBZ40Stws/uGZ1sWjqwF33FMpmfYHSOpu0NUdO2MsazXGpHnZEBqE2v0pOlYiZJxoR/wIQ7NyyqG2XTh4C7IORJVNOx+4TLg1/JYRI/SfLHEGO2bl6v7u+0mEfCM+aa2ZQdITK0YI6kYjxqqnq9GPL7CVQgW3JG4zMHjzLGS7qo87mJw/XoXaFX3rUwuEVyODIYmVBnYeaHQeQkr7EPOTvtpsXAGQdlBHlEypmoEcUl2xi182eywvIBfqqqs5xDGaiRgjCi2SWzSiTnGisYKgfWdw0fEXEQzro
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: loki
    type: Opaque
