apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  values:  
    resources:
      # set resource requests so that istiod can run on local Kind envs
      requests:
        cpu: 1m
        memory: 1Mi
    
