apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: metallb
      version: 0.15.3  # see https://github.com/metallb/metallb/releases
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 12h
  values:
    crds:
      enabled: true
    controller:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
    speaker:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
