---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: http_error_hourly
  namespace: alloy
  labels:
    log_to_alert: "yes"
spec:
  groups:
  # use service_name if matching on envoy logs from the container (istio-proxy)
  - name: http-errors
    interval: 1m
    rules:
    - alert: http_error_hourly
      expr: sum(rate({service_name="envoy"} |~ `HTTP/1.1\\" 50` [60m])) by (instance) > 60
      labels:
        severity: warning
      annotations:
        summary: "http error in 500 range code found"
        description: "desc: all labels {{ $labels }} {{ $labels.instance }}"
