apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  chart:
    spec:
      version: "2.16.2"
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    args:
    # this label-selector ensures the havenplus sealed-secrets controller 
    # doesn't collide with the quattro sealed-secrets controller
    - "--label-selector"
    - "havenplus.commonground.nl/sealed-secrets" 
