---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  labels:
    havenplus.commonground.nl/sealed-secrets: ""
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgCbJqmjFh9s+SFeF8lQ+jXatFsXCqJcXW7B1i+VnCTA4kWU74dE1Yr5gPAV8cjcs2ejKrWM2JXPeWKJA92nWFaFalshu6RLaiHY3TyRcHz3fF6F2YktoB7U5Azde+TziVwh3uiaPI+piBQF+4Q79StGzR/DEzoMaxWx8Or+r4E9ODBxRyXCDVMPSZ6S2x++ARQjyI8Y1PEuWXcNXnPfTYLJTgdA2W1txc7w16gH+/8TtlqZocUhwcCzyRQroskL1Z8MfvouVmjFyFwZABPHIlJjFWeZUlcxFyejg7wkV4AYP99fxtjsdm/xr6Qs0uKkPqUb/9qzdRW6W3lXbxnAIVJmW0S3zGxMqdb8/gsACUaqrDCbUsyxLLegUYWBH0B2GIVW2vrfu5eO3RXGCA3hP4SymSa+qF8/clC6CyBhmUEPwVy1SRgCq/Rx4ycIbtBKdZV0WBN281+YvAEHO9Gj8iTlcoNdVWHEk638DKvEyDoeC3NVwEEdxvwAcKNO3MqdBfM57bRoxr8wPGBiDSrCPkverxFSiReKYq/uqfd7ROo9PH17CydCExZ1t3ELi6PFY2pv8gEkonRn/E/afZpeW3zggh+a2JOz96+iQNG777MxHpB41rAlNH77aliYlzugmMed/QE5qf8hq6rWURQMQ2AC3Ma1VZlw46xZBF1g4V9E3lcCTbnwq0wMrFn0j5LdKx3Nnw/grueiWd3Q3wcp4EOezfageQ==
    S3_SECRET_ACCESS_KEY: AgAqPMPw5+GEUwYYpMMrZF2BcDximJfWC3PDbOYYbm3WpQps6u8RKLLT7+7fInJTUQF85HWEzp38Sm8BURx37uGXWx3ZEoGRbw+Npg6XjfJTOUZBrm7eKAA06iEUtIrfrQeFFuiiQ12PzcItPv7+t/f8yvyjMQzSo6G+a6P/Khy7ptY8lsv+5/0JDiU1Nha9+2iHCIG1YQ4uZIWeeacnuYXyIDWJxqpFFsNJl5iD+5oFy4juCua/VkHjL7zMLTYpizzmDzGXss7UYo9LhKoPGoU0uDdAk9LswO9QCAAoNntYwTHv/1mIGFhHeCPQUbY0h9HcAnGy+laPONLtw+ADpQSIaihyOsEOOKem2pEuThFeoSJlclBkMe5AfOZXp5csqDXE/F0Jez2BzdQ6i0ub7HoCMa9E4iKuvAl6QIvCayoI/9KPpHcNVO1qBM6vodbffagFffOxlHCCKAl5pCZCDzaUS5roInaAKiDbZqNbZUsG73L/wnpeY1zz6XQluUZZaULQ5qUsS0lSkEO8OCaQagnTAlBupEF1bn2rE9GawgVbrd/5v0O9DpJaRAotcqnSawsgODU8cTRhkr1H9iiWVZw67bKhfs6KmaWDXOXplrCdu/FTku8iBzYI+f2RCKSDYV72fguFNdXEIfs50d406y/mn/MDU1xBA6Y4qVFkTgXzfnmKu/fKOmjybK7CAqIxN/pJoYVGCszLfyJ+dZB4zY2dFqGA1EStiIQHyQwVffPSRyizJ75ZNmb4
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: mimir
    type: Opaque
