apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
spec:
  interval: 30m
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: operator
      version: "set-in-overlay"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
      interval: 12h
   