apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
spec:
  chart:
    spec:
      version: "5.0.1"
  values:
    resources:
      # disable resource requests so that falco can run on local Kind envs
      requests:
        cpu: 1m
        memory: 1Mi
    falcosidekick:
      replicaCount: 1
