apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  labels:
    app: s3-proxy
    app.kubernetes.io/name: s3-proxy
  name: s3-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
