apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chart:
    spec:
      version: "24.2.3"
  values:
    production: true
    proxyHeaders: "xforwarded"
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: authn.example.domain.tld
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls: true
